version: "3.3"
services:
  app:
    container_name: criverostenpo-api
    image: spring-boot-criverostenpo/criverostenpo-api
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=public